-- Run in Supabase SQL Editor. Add users in Auth, then set public.profiles.role = 'admin'.
create type public.content_status as enum ('draft','published','archived');
create table public.profiles (id uuid primary key references auth.users on delete cascade, role text not null default 'editor' check (role in ('admin','editor')), created_at timestamptz default now());
create table public.projects (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, type text not null, summary text, body jsonb default '{}'::jsonb, stack text[] default '{}', status public.content_status default 'draft', featured boolean default false, visible boolean default true, sort_order int default 0, cover_media_id uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.content_items (id uuid primary key default gen_random_uuid(), collection text not null check (collection in ('apps','websites','experiments','skills','journey','milestones','faqs','social_links','homepage_sections','site_settings')), slug text, title text not null, data jsonb default '{}'::jsonb, status public.content_status default 'draft', visible boolean default true, featured boolean default false, sort_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.media (id uuid primary key default gen_random_uuid(), name text not null, alt_text text, path text not null unique, mime_type text, size_bytes bigint, created_at timestamptz default now());
create table public.messages (id uuid primary key default gen_random_uuid(), name text not null, email text not null, subject text, message text not null, read_at timestamptz, created_at timestamptz default now());
alter table public.projects add constraint projects_cover_media_fk foreign key (cover_media_id) references public.media(id) on delete set null;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
alter table public.projects enable row level security; alter table public.content_items enable row level security; alter table public.media enable row level security; alter table public.messages enable row level security;
create policy "public published projects" on public.projects for select using (status='published' and visible); create policy "admins manage projects" on public.projects for all using (public.is_admin()) with check (public.is_admin());
create policy "public published content" on public.content_items for select using (status='published' and visible); create policy "admins manage content" on public.content_items for all using (public.is_admin()) with check (public.is_admin());
create policy "public view media" on public.media for select using (true); create policy "admins manage media" on public.media for all using (public.is_admin()) with check (public.is_admin());
create policy "anyone can submit messages" on public.messages for insert with check (true); create policy "admins read messages" on public.messages for select using (public.is_admin());
insert into storage.buckets (id,name,public) values ('portfolio-media','portfolio-media',true) on conflict do nothing;
create policy "public media downloads" on storage.objects for select using (bucket_id='portfolio-media'); create policy "admins manage uploads" on storage.objects for all using (bucket_id='portfolio-media' and public.is_admin()) with check (bucket_id='portfolio-media' and public.is_admin());
